---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: http-https-echo
spec:
  replicas: 1
  template:
    spec:
      containers:
      - name: http-https-echo
        # image: mendhak/http-https-echo:30
        image: mendhak/http-https-echo:29
        imagePullPolicy: Always
        env:
        - name: ECHO_INCLUDE_ENV_VARS
          value: "1"
        # - name: __VERSION
        #   value: "@30"
        - name: __VERSION
          value: "@29"
        ports:
        - name: http
          containerPort: 8080
