---
kind: Service
apiVersion: v1
metadata:
  name: http-https-echo
  namespace: default
spec:
  # type: ClusterIP
  type: LoadBalancer
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: http
