---
apiVersion: v1
kind: Namespace
metadata:
  name: argocd
---
apiVersion: v1
kind: Namespace
metadata:
  name: awx
---
apiVersion: v1
kind: Namespace
metadata:
  name: examples
---
apiVersion: v1
kind: Namespace
metadata:
  name: monitoring
