---
kind: Service
apiVersion: v1
metadata:
  name: http-https-echo
  namespace: default
spec:
  type: LoadBalancer
  selector:
    app.kubernetes.io/name: http-https-echo
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: http
