---
name: CI - OCI OKE Kubectl

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - '*'

# See: https://github.com/marketplace/actions/configure-kubectl-for-oracle-container-engine-for-kubernetes-oke
env:
  # user=ocid1.user
  OCI_CLI_USER: "${{ secrets.OCI_CLI_USER }}"
  # tenancy=ocid1.tenancy
  OCI_CLI_TENANCY: "${{ secrets.OCI_CLI_TENANCY }}"
  # fingerprint=99:87
  OCI_CLI_FINGERPRINT: "${{ secrets.OCI_CLI_FINGERPRINT }}"
  # key_file=sandbox.pem
  OCI_CLI_KEY_CONTENT: "${{ secrets.OCI_CLI_KEY_CONTENT }}"
  # region=us-sanjose-1
  OCI_CLI_REGION: "${{ secrets.OCI_CLI_REGION }}"

jobs:
  kubectl:
    name: Apply
    runs-on: ubuntu-latest
    steps:
      - name: Check out the codebase.
        uses: actions/checkout@v4

      - name: Configure kubectl.
        uses: oracle-actions/configure-kubectl-oke@v1.3.2
        with:
          cluster: ${{ secrets.OKE_CLUSTER_OCID }}

      - name: Configure helm.
        uses: azure/setup-helm@v3
        with:
          version: 'latest' # default is latest (stable)
          token: ${{ secrets.GITHUB_TOKEN }} # only needed if version is 'latest'

      - name: Show kubectl version.
        run: kubectl version

      - name: Show helm version.
        run: helm version

      - name: List all namespaces.
        run: kubectl get ns

      - name: Run apply.
        run: (cd k8s_manifests && make apply)

      - name: Sleep.
        run: sleep 10

      - name: Set PUBLIC_IP.
        run: echo "PUBLIC_IP=$(kubectl get svc http-https-echo --namespace examples --output jsonpath='{.status.loadBalancer.ingress[0].ip}')" >> $GITHUB_ENV

      - name: Show PUBLIC_IP.
        run: echo ${PUBLIC_IP}

      - name: Curl public ip endpoint.
        run: curl -fsSL --connect-timeout 5 --max-time 30 http://${PUBLIC_IP}/

      - name: Grep __VERSION from curl response.
        run: curl -fsSL --connect-timeout 5 --max-time 30 http://${PUBLIC_IP}/ | grep __VERSION | xargs
